### ISSUE TITLE
[Help]Can't work on China server, what can I do to help you fix it

### ISSUE THREAD

**Issue by xkkmoe** [InitialDet/AutoHook#25]
logs

12:34:05.677 | ERR [LOCALPLUGIN] Error while loading Auto Hook
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.InvalidEnumArgumentException: Value does not fall within the expected range.
   at Parser.FishingParser.Regexes.FromLanguage(ClientLanguage lang)
   at Parser.FishingParser..ctor()
   at AutoHook.FishTimer.HookingManager..ctor()
   at AutoHook.AutoHook..ctor(DalamudPluginInterface pluginInterface)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in D:\a\Dalamud\Dalamud\Dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in D:\a\Dalamud\Dalamud\Dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 414
--------------------------------
12:34:05.678 | INF [PLUGINM] Regular plugin failed to load, adding anyways: AutoHook.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.InvalidEnumArgumentException: Value does not fall within the expected range.
   at Parser.FishingParser.Regexes.FromLanguage(ClientLanguage lang)
   at Parser.FishingParser..ctor()
   at AutoHook.FishTimer.HookingManager..ctor()
   at AutoHook.AutoHook..ctor(DalamudPluginInterface pluginInterface)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in D:\a\Dalamud\Dalamud\Dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in D:\a\Dalamud\Dalamud\Dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 414
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in D:\a\Dalamud\Dalamud\Dalamud\Plugin\Internal\PluginManager.cs:line 771

**Comment by InitialDet** [comment]
The plugin currently does not support the CN server, I'll be looking to fix this when I get the time.

**Comment by NiGuangOwO** [comment]
> The plugin currently does not support the CN server, I'll be looking to fix this when I get the time.

I've tried to fix it #26

**Comment by InitialDet** [comment]
I've added a new version, can you guys tell me if it works?

**Comment by xkkmoe** [comment]
> I've added a new version, can you guys tell me if it works?

it works ! thanks u . its legendary plugin !
